apiVersion: v1
kind: Service
metadata:
  name: {{ template "common.names.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Chart.Name }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if (or (eq .Values.service.type "LoadBalancer") (eq .Values.service.type "NodePort")) }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy | quote }}
  {{- end }}
  {{- if eq .Values.service.type "LoadBalancer" }}
  loadBalancerSourceRanges: {{ .Values.service.loadBalancerSourceRanges }}
  {{- end }}
  {{- if (and (eq .Values.service.type "LoadBalancer") (not (empty .Values.service.loadBalancerIP))) }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  ports:
  {{- if (hasKey .Values.service "internalPort") }}
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.internalPort }}
      protocol: TCP
  {{- end }}
  {{- if (hasKey .Values.env "SDK_SERVER_PORT") }}
    - port: {{ .Values.env.SDK_SERVER_PORT }}
      protocol: TCP
      name: sdkapi
      targetPort: sdkapi
  {{- end }}
  {{- if (hasKey .Values.env "BACKEND_SERVER_PORT") }}
    - port: {{ .Values.env.BACKEND_SERVER_PORT }}
      protocol: TCP
      name: backendapi
      targetPort: backendapi
  {{- end }}
  {{- if .Values.diagnosticMode.enabled }}
    - name: debug
      port: {{ .Values.diagnosticMode.debug.port }}
      targetPort: {{ .Values.diagnosticMode.debug.internalPort }}
      protocol: TCP
  {{- end }}
  selector: {{- include "common.labels.matchLabels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Chart.Name }}
